version: '3.8'

services:
  cpu-scheduler:
    build: .
    container_name: cpu_scheduler_app
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
